language: r
warnings_are_errors: true

r_github_packages:
  - wrathematics/RNACI

notifications:
  email:
    on_success: change
    on_failure: change
env:
  - global:
    - _R_CHECK_FORCE_SUGGESTS_=0

